### ISSUE TITLE
swift 中如何引用  以下方法

### ISSUE THREAD

**Issue by mark644873613** [RocketsChen/CDDPagerController#1]
self.setUpDisplayStyle { (titleScrollviewBgColor, norColor, selColor, proColor, titleFont, titleButtonWidth, isShowProgressView, isOpenStretch, isOpenShade) in

     }

**Comment by erHomeJi** [comment]
同问，希望楼主回复

**Comment by RocketsChen** [comment]
[CDDPagerController-Swift](https://github.com/RocketsChen/CDDPagerController-Swift) 可以去参考下
