### ISSUE TITLE
请问当隐藏和显示导航栏时，怎样使标题随着导航栏的隐藏/显示修改位置和大小呢？

### ISSUE THREAD

**Issue by trembleCat** [RocketsChen/CDDPagerController#4]
![1](https://user-images.githubusercontent.com/34125231/56425678-eaeed980-62e7-11e9-89dc-d6a2bce3eccb.png)
![2](https://user-images.githubusercontent.com/34125231/56425681-ede9ca00-62e7-11e9-95af-454f4f5e162d.png)

**Comment by RocketsChen** [comment]
你可以在你监听隐藏或显示的回调里这样做，这里我以通知为例，点击了隐藏导航栏按钮后的响应：
```
__weak typeof(self)weakSelf = self;
[[NSNotificationCenter defaultCenter] addObserverForName:@"changeFrame" object:nil queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification * _Nonnull note) {
    
    [weakSelf.navigationController setNavigationBarHidden:YES animated:NO];
    
    [super viewDidLayoutSubviews];  // 关键
    
}];
```

关键就是调用重新布局方法，至于导航栏在什么时候隐藏这个看你需求。仅供参考！
如若不理解，可查看框架源码的布局部分。
