### ISSUE TITLE
滑动列表或者点击顶部标签 怎么控制刷新列表呢？

### ISSUE THREAD

**Issue by kuyona** [RocketsChen/CDDPagerController#7]
- (void)setUpAllChildViewController
{
    NSArray *titles = @[@"全部",@"审核中",@"被驳回",@"已上架",@"已下架"];
    for (NSInteger i = 0; i < titles.count; i++) {
        YZCMyStoreListController *vc = [YZCMyStoreListController new];
        vc.title = titles[i];
        vc.index = i;
        [self addChildViewController:vc];
    }
}
大佬你好 比如有五个列表、第一次进去的时候会加载刷新、在其中一个列表比如已上架列表操作下架功能、怎么控制已下架列表去刷新呢

**Comment by RocketsChen** [comment]
记录当前页面是否已经创建在内存中，有回调过去刷新，没有第一次打开默认会有刷新
