### ISSUE TITLE
导航标签滑动或者点击时如何做到切换的页面数据实时刷新？在线求助大佬

### ISSUE THREAD

**Issue by kuyona** [RocketsChen/CDDPagerController#8]
addChildViewController五个子控制器，每个加载的数据不同。导航标签滑动或者点击时如何做到切换的页面每次都加载数据实时刷新？

**Comment by RocketsChen** [comment]
这个是具体页面控制的 不是框架控制的

**Comment by kuyona** [comment]
但是框架加载子控制器只会加载一次，想让它滑动点击时都去加载 这要咋处理呢？
